#!/bin/sh
# Run this only if you have changed a Makefile.am, configure.ac file or
# if you want to use other version of autoconf / automake

aclocal
libtoolize --force
autoheader
automake --add-missing
autoconf

